import tkinter as tk

window = tk.Tk()
window.title("Handmade With Love")
window.geometry("330x330")
window.configure(bg="#f5e2e3")
label=tk.Label(window, text= "Handmade With Love")
label.configure(bg="#f5e2e3")
username_label=tk.Label(window, text="Username")
username_entry=tk.Entry(window)
password_label=tk.Label(window, text="Password")
password_entry=tk.Entry(window, show="*")
login_button=tk.Button(window, text="Login")
label.pack()
window.mainloop()